name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
  schedule:
    - cron: "0 6 * * *" # daily at 6am

jobs:
  compliance:
    name: ğŸ”
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: "src"
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - uses: actions/setup-node@v6
      - run: pip install typos yamllint gersemi
      - run: npm install prettier prettier-plugin-toml
      - run: typos src
      - run: yamllint src
      - run: gersemi --check src
      - run: npx prettier . --check --plugin prettier-plugin-toml

  lint:
    name: âœ¨
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install libblas-dev liblapack-dev
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          pip-install: -e .[lint]
          cache: pip
      - run: ruff format --diff
      - run: ruff check
      - run: >
          find . -type f \( -name "*.cpp" -o -name "*.cu" \) |
          xargs clang-format --dry-run --Werror

  test:
    name: âš™ï¸
    needs: [compliance, lint]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        py:
          # - "3.10"
          # - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
        # include:
        #   - os: macos-latest
        #     py: "3.14"
        #   - os: windows-latest
        #     py: "3.14"
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install libblas-dev liblapack-dev
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.py }}
          pip-install: -e .[test]
          cache: pip
      - run: pytest -v test/
      - working-directory: test/cpp
        run: >
          ctest --build-and-test . build/
          --build-generator Ninja
          --test-command ctest -V

  dev-container:
    name: ğŸ³
    needs: [compliance, lint]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - run: >
          docker buildx build .
          --file docker/Dockerfile.ubuntu
          --tag ubuntu
          --load
      - run: >
          docker run
          --rm
          -v "$PWD:/app"
          -w /app
          ubuntu
          pip install -e .[lint,test]
