name: ci

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  lint:
    name: ✨
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install libblas-dev liblapack-dev
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          pip-install: -e .[lint]
          cache: pip
      - run: ruff format --diff
      - run: ruff check
      - run: yamllint .
      - run: >
          find . -type f \( -name "*.cpp" -o -name "*.cu" \) |
          xargs clang-format --dry-run --Werror

  test:
    name: ⚙️
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        py:
          # - "3.10"
          # - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
        # include:
        #   - os: macos-latest
        #     py: "3.14"
        #   - os: windows-latest
        #     py: "3.14"
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install libblas-dev liblapack-dev
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.py }}
          pip-install: -e .[test]
          cache: pip
      - run: pytest -v test/
